---
title: "Week 4: Syntax"
subtitle: "Recitation for LING 201:02"
author: "Quartz Colvin (they/them)"
institute: "Rutgers University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["rutgers", "rutgers-fonts"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      bibliography:  bibliography.bib
    keep_tex: true
header-includes:
- \usepackage{qtree}
- \newenvironment{dummy}{}{}
documentclass: ../includes/tex
---

class: middle, center 

# Constituents!

---

# Constituents 

***A group of words that acts together as a unit***

- a basic structure in syntax

--

Some examples

- **Justin** teaches linguistics.

- **My cat** likes rice.

- **That tall guy from NJ** likes philosophy.

--

Even though the bold constituents can have only one word or several, they act as a unit to describe a single concept.

---

# Constituents: phrases

**Phrases** are types of constituents 

--

Each phrase has a main word (or **head**), and phrases are named after the head word's part of speech.

---

# Constituents: phrases

- Noun phrase (NP)
  
  - *woman, the woman, the happy woman, the woman with the hat*
  
- Prepositional phrase (PP)

  - *into the forest, by the author, for good luck*

- Verb phrase (VP)

  - *eats, eats pizza, eats quickly, eats pizza quickly at midnight*
  
- Adjective phrase (AdjP)

  - *happy*
  
- Adverb phrase (AdvP)

  - *quickly*

**Note that one constituent may contain another, smaller constituent.**

---

class: center, middle

# Constituency tests!

---

# Constituency tests 

1. replacement/substitution 

2. stand-alone

3. movement 

4. coordination 

**As is usually the case, these tests don't work 100% of the time, so you should try multiple**

---

# Constituency tests 

## Replacement (AKA substitution)

Consider the following sentence ([the happy student] and [in New Brunswick] are constituents)

- [The happy student] lives [in New Brunswick]

---

# Constituency tests

## Replacement


**Replacement test:** try replacing a group of words with a *pro-form* (a pronoun or another generic expression such as *there, like that, do, do that, that way*).

If it works, then the words are a constituent.

--

- [The happy student] lives in New Brunswick → [She] lives in New Brunswick
  
  - this works, so [the happy student] is a constituent!

--

- The happy student [lives in New] Brunswick → The happy student [??] Brunswick

  - this doesn't work, so [lives in New] is not a constituent 

***what about replacing [in NB] with a pro-form? how about [the happy] or [student lives]?***

---

# Constituency tests 

## Stand alone

**Stand alone test:** try coming up with a question that can be answered by just saying the group of words you want to test on its own

- Who lives in New Brunswick? [The happy student]!

  - this works, so [the happy student] is a constituent
  
***can you try the stand alone test with [in NB]? what about [the happy] or [student lives]?***

---

# Constituency tests  

## Movement 

**Movement test:** try moving a group of words to a different part of the sentence, like the beginning or end of the sentence. You *may* need to add extra words to support this movement.

- The person who lives in New Brunswick is [the happy student].

  - this works, so [the happy student] is a constituent
  
- Student who lives in New Brunswick is [the happy]

  - this doesn't work, so [the happy] is not a constituent
  
***can you try the movement test with [in NB]? how aboout [in New] or [student lives]?***



---

# Constituency tests 

## Coordination 

**Coordination test:** coordinating conjunctions like *and* or *or* will always join two words or phrases of the same type. So, if a group of words is a constituent, you should be able to insert another phrase of the same type joined with *and* or *or*

- [The happy student] and [the grumpy professor] live in New Brunswick.

  - this works, so [the happy student] is a constituent
  
***can you try the coordination test with [in NB]? how about [student lives] or [in New]?***

---

class: middle, center

# Practice!

---

# Practice 

**Use the constituency tests (replacement, movement, stand alone, coordination) to determine whether the bold/red sequences of words are constituents:

--

1. **The tragedy** upset the entire family.

2. They hid **in the cave**.

3. The **computer was very** expensive.

4. The geese **swam across** the lake.

5. Mary gave **a book to her sister.**

6. Linda read **a book about geology.**

